[package]
name = "password_database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.4"
rand = "0.8.5"
sqlite = "0.31.0"
cpython = "0.7.1"
